# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 07:24
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0002_auto_20170117_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.TextField(blank=True, max_length=500)),
                ('assessment_id', models.TextField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Value Supplied')])),
                ('last_start_time', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Profile')),
            ],
        ),
    ]
