# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dictator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='assessment_id',
            field=models.TextField(max_length=100),
        ),
    ]
