# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dictator', '0003_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='profile_catagory',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
