# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 07:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.TextField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Value Supplied')]),
        ),
    ]
