# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 15:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170117_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.TextField(blank=True, default=b'user', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Invalid Value Supplied')]),
        ),
    ]
